### ISSUE TITLE
question about word embedding layer

### ISSUE THREAD

**Issue by zarzen** [baaesh/CNN-sentence-classification-pytorch#1]
Hi 
I see the 'unk' initialized and placed at the `0` index of the embedding at
[here](https://github.com/baaesh/CNN-sentence-classification-pytorch/blob/master/model.py#L27)
but the `padding_idx=1`, does it suppose to be `0`?

**Comment by nesat** [comment]
<unk> token is placed at index 0 as you mentioned and <pad> at index 1. They are two different tokens where <unk> is used for words outside word embedding vocabulary and <pad> is used to fix the size of inputs. Thats why embedding of <unk> is a random initialized vector but embedding of <pad> is zero vector

**Comment by nesat** [comment]
\<unk> token is placed at index 0 as you mentioned and \<pad> at index 1. They are two different tokens where \<unk> is used for words outside word embedding vocabulary and \<pad> is used to fix the size of inputs. Thats why embedding of \<unk> is a randomly initialized vector but embedding of \<pad> is zero vector
